### ISSUE TITLE
Using output dir with multiple query files with same basename overwrites files

### ISSUE THREAD

**Issue by sadmansakib** [jschaf/pggen#28]
### pggen release: 2021-04-18

Code generation failed for following example configuration:

```   
 pggen gen go \
	 --schema-glob '${schema_path}/*.up.sql' \
	 --query-glob '${query_path}/A/query.sql' \
	 --query-glob '${query_path}/B/query.sql' \
	 --query-glob '${query_path}/C/query.sql' \
	 --query-glob '${query_path}/D/query.sql' \
	 --query-glob '${query_path}/E/query.sql' \
	 --query-glob '${query_path}/F/query.sql' \
	 --go-type 'int8=int8' \
	 --go-type 'int=int' \
	 --go-type 'varchar=string' \
	 --postgres-connection '${db_url}' \
	 --output-dir 'db'  
```
result : `generated 6 query files`

Although pggen is generating Codes for only F query directory and entire DBQuerier and Querier interface is missing from the output directory. I am using golang migrate for maintaining database migrations so my db schema are in A.up.sql format in schema directory

**update:** renaming query.sql files  generates all codes. it seems pggen is overwriting generated codes because of same file name

**Comment by jschaf** [comment]
Yep, definitely a bug. It sounds like pggen is trying to reuse the query.sql.go name for each directory `A`, `B`, ..., `F`. The `F` directory wins since it's last.

I think I'll use the following name algorithm:

- If output dir is not set, just use the base name since they file names can't collide, i.e. `query.sql` to `query.sql.go`.
- If output dir is set, make the generated names unique by:
  - using the parent directory as a prefix, e.g. `A/query.sql` to `db/A_query.sql.go`
  - If there's still a collision (if grandparent directory is different), append a digit starting from 1, e.g. 
    - `dir1/A/query.sql` to `A_query_1.sql.go`
    - `dir2/A/query.sql` to `A_query_2.sql.go`

**Comment by sadmansakib** [comment]
Is it possible to generate the `query.sql.go` from the first folder than traverse other folders and append generated code to the existing `query.sql.go` file?

**Comment by jschaf** [comment]
I prefer the conceptual simplicity of 1 query file producing 1 go file. Though, it wouldn't be too hard to do it after the fact with a sed script.
