### ISSUE TITLE
Validate idea (result columns by view creation) WIP

### ISSUE THREAD

**Issue by aight8** [jschaf/pggen#38]
investigate and validate:

- create view by pggen query (only select queries?)
- pggen.args -> use default value of type, is this step needed?
- goal: better result column analysis -> is it really better?

**Comment by jschaf** [comment]
Interesting, so the idea is given a source query like `SELECT 3 * pggen.arg('foo')`, create a view like:

```sql
CREATE VIEW pggen_foo_view AS
SELECT 3 * null -- or a default value
```
1. Yep, I think it would only work for select queries. Maybe you can put inserts and updates in CTEs?

2. Currently, pggen, runs the query using null for all the parameters. Null has the nice property of working for all values. I worked on that section code of yesterday. The reason it works is that Postgres still reports the types even if there was a constraint violation caused by using null.

3. I'm not sure if the column analysis with a view is more informative than by running the query. Maybe there's something interesting in the catalog tables?

I think the most promising method is to use the explain plan. pggen already has the explain plan and uses it a bit in `inferOutputNullability`.

**Comment by jschaf** [comment]
I think there's too many potential issues to pursue it:

- The view won't provide any additional information beyond what we can get by running the query.

- Won't work for insert, update, delete queries.

- It's not clear what the views would be useful for and how to keep them up to date.
